#!/bin/bash

for opt in "$@"; do
    if [ "${opt}" == "--bash-completion" ]; then
	cat "${APPDIR}/usr/bin/____cli_name____-completion.bash"
        exit 0
    fi
done

export COGNAC_HELP_APPEND="$(echo -en '\t--bash-completion\tprint bash completion(appimage only)\n\t--appimage-help\t\tappimage helps')"

LD_LIBRARY_PATH=${APPDIR}/usr/lib/ "${APPDIR}/usr/bin/____cli_name____" "$@"
