name: Bug Report
description: Report a reproducible bug or regression
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill in as much detail as possible.

  - type: input
    id: title
    attributes:
      label: Bug Summary
      description: A short summary of the bug
      placeholder: e.g., Crash on startup
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps needed to reproduce the issue
      placeholder: |
        1. Open a terminal
        2. Run: `my-cli-tool init --config config.yaml`
        3. Run: `my-cli-tool deploy`
        4. Observe the error in the output
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Project Version
      description: What version are you using?
      placeholder: e.g., v1.2.3

  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: Include OS, language/runtime, configuration, etc.
